/**
 * CJGate ⇄ Midnight Preprod helper.
 *
 *   npm run cjgate:preprod:init      - create (if needed) + sync the dedicated
 *                                      CJGate Preprod wallet, print its PUBLIC
 *                                      address and PUBLIC balance
 *   npm run cjgate:preprod:address   - print ONLY the public Preprod address
 *   npm run cjgate:preprod:deploy    - deploy the current CJGate contract to
 *                                      Preprod (via the scaffold deploy flow)
 *   npm run cjgate:preprod:live -- --source <path>
 *                                    - real Gitleaks + Semgrep + real ZK proof
 *                                      + real Preprod transaction
 *
 * Wallet policy:
 *   - A DEDICATED wallet, generated by CJGate and stored under
 *     `.midnight-state.json` → wallets.preprod (gitignored, mode 0600).
 *   - `MIDNIGHT_WALLET_MNEMONIC` / `MIDNIGHT_WALLET_SEED` are IGNORED here so a
 *     browser-wallet phrase is never reused or exposed.
 *   - The wallet is created at most once and then reused; sync state is cached
 *     under `.midnight-wallet-state/preprod/`.
 *
 * This script prints ONLY public values: wallet address, public balance,
 * contract address, transaction id, block height, public `policyPassed`.
 * It never prints the mnemonic, seed, private keys, witness values, scanner
 * findings, or finding counts.
 */
import { execFileSync } from 'node:child_process';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocket } from 'ws';

import {
  NETWORK_CONFIGS,
  loadState,
  getOrCreateWallet,
  getDeployment,
  setActiveNetwork,
  type NetworkId,
  type NetworkConfig,
} from '../src/network.js';
import {
  createWallet,
  persistWalletState,
  unshieldedToken,
  deriveUnshieldedAddress,
} from '../src/wallet.js';

// @ts-expect-error wallet sync + indexer WS need a global WebSocket
globalThis.WebSocket = WebSocket;

const NETWORK = 'preprod' as const;
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function die(msg: string, code = 1): never {
  console.error(`cjgate:preprod: ${msg}`);
  process.exit(code);
}

/** Remove any imported-wallet env so only the dedicated CJGate wallet is used. */
function scrubImportedWalletEnv(): NodeJS.ProcessEnv {
  const hadImport = !!(process.env.MIDNIGHT_WALLET_MNEMONIC || process.env.MIDNIGHT_WALLET_SEED);
  if (hadImport) {
    console.log('note: ignoring MIDNIGHT_WALLET_* — CJGate Preprod uses its own dedicated wallet');
  }
  delete process.env.MIDNIGHT_WALLET_MNEMONIC;
  delete process.env.MIDNIGHT_WALLET_SEED;
  // Never echo the 24-word phrase from any downstream scaffold command.
  process.env.CJGATE_QUIET_WALLET = '1';
  const childEnv: NodeJS.ProcessEnv = { ...process.env };
  delete childEnv.MIDNIGHT_WALLET_MNEMONIC;
  delete childEnv.MIDNIGHT_WALLET_SEED;
  childEnv.CJGATE_QUIET_WALLET = '1';
  return childEnv;
}

function persistedPreprodWallet(): { seed: string } | null {
  const w = loadState()?.wallets?.[NETWORK];
  return w?.seed ? { seed: w.seed } : null;
}

/**
 * `getOrCreateWallet` flips `.midnight-state.json.activeNetwork` when it
 * generates a wallet. CJGate's Preprod tooling always targets Preprod
 * explicitly, so keep the global default (the local devnet flow) untouched.
 */
function keepActiveNetwork<T>(fn: () => T): T {
  const prev: NetworkId = loadState()?.activeNetwork ?? 'undeployed';
  const out = fn();
  setActiveNetwork(prev);
  return out;
}

// ── sync engine ──────────────────────────────────────────────────────────────
//
// Why this is not just `await wallet.waitForSyncedState()`:
//
// The wallet SDK's unshielded child (wallet-sdk-unshielded-wallet@3.1.0,
// dist/v1/RunningV1Variant.js) wraps its sync stream in
// `Stream.tapError(Console.error) → Stream.retry(exponential backoff, no
// recurrence cap)`. A `SyncWalletError` ("Wallet.Sync: [object Object]") is
// therefore logged and retried FOREVER internally. Its `state.progress` never
// reaches `isStrictlyComplete()`, so `unshielded.waitForSyncedState()` — and
// hence `facade.waitForSyncedState()` — never resolves and never rejects. The
// caller then just waits out its own outer timeout.
//
// This engine instead observes `facade.state()`, tracks per-child sync
// progress, and treats "no progress for a while" as a failed attempt. It then
// re-creates the wallet from the persisted state (a genuine resume) and
// retries a bounded number of times with backoff, before either reporting
// real progress ("re-run to resume") or surfacing a sanitized permanent error.

type ChildProgress = { applied: bigint; highest: bigint; connected: boolean; complete: boolean };
type SyncProgressView = { unshielded: ChildProgress; shielded: ChildProgress; dust: ChildProgress };

type SyncOutcome = {
  status: 'synced' | 'progressing' | 'failed';
  facadeState: unknown;
  progress: SyncProgressView | null;
  attempts: number;
  elapsedMs: number;
  syncErrorCount: number;
  reason?: string;
};

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

function toBig(v: unknown): bigint {
  try {
    return typeof v === 'bigint' ? v : BigInt((v as number | string) ?? 0);
  } catch {
    return 0n;
  }
}

function maxBig(...vs: unknown[]): bigint {
  let m = 0n;
  for (const v of vs) {
    const b = toBig(v);
    if (b > m) m = b;
  }
  return m;
}

function readChild(p: any): ChildProgress {
  // The unshielded child reports transaction-id progress
  // (`appliedId`/`highestTransactionId`); the shielded and dust children report
  // Merkle-index progress (`appliedIndex`/`highestIndex`/…). Completeness is
  // taken from the SDK's own `isStrictlyComplete()` on every shape.
  let complete = false;
  try {
    complete = typeof p?.isStrictlyComplete === 'function' ? Boolean(p.isStrictlyComplete()) : false;
  } catch {
    /* ignore */
  }
  const applied = maxBig(p?.appliedId, p?.appliedIndex);
  const highest = maxBig(
    p?.highestTransactionId,
    p?.highestIndex,
    p?.highestRelevantIndex,
    p?.highestRelevantWalletIndex,
  );
  return { applied, highest, connected: Boolean(p?.isConnected), complete };
}

/**
 * Per-child sync progress from a facade state. Guarded — never throws.
 * Field paths match `FacadeState.isSynced` in wallet-sdk-facade: unshielded at
 * `.progress`, shielded/dust at `.state.progress`.
 */
function progressOf(fs: any): SyncProgressView {
  return {
    unshielded: readChild(fs?.unshielded?.progress),
    shielded: readChild(fs?.shielded?.state?.progress ?? fs?.shielded?.progress),
    dust: readChild(fs?.dust?.state?.progress ?? fs?.dust?.progress),
  };
}

/** Monotonic-ish "has anything advanced" proxy. */
function appliedSum(p: SyncProgressView): bigint {
  return p.unshielded.applied + p.shielded.applied + p.dust.applied;
}

function progressKey(p: SyncProgressView): string {
  const k = (c: ChildProgress) => `${c.applied}/${c.highest}/${c.connected ? 1 : 0}/${c.complete ? 1 : 0}`;
  return `${k(p.unshielded)}|${k(p.shielded)}|${k(p.dust)}`;
}

/** Print sync progress using transaction indices only — no wallet data / secrets. */
function printSyncProgress(p: SyncProgressView): void {
  const row = (name: string, c: ChildProgress) =>
    `    ${name.padEnd(10)} applied ${c.applied} / highest ${c.highest}  connected=${c.connected}  complete=${c.complete}`;
  console.log('  sync progress (chain transaction indices only):');
  console.log(row('unshielded', p.unshielded));
  console.log(row('shielded', p.shielded));
  console.log(row('dust', p.dust));
}

/**
 * Temporarily filter the wallet SDK's raw "Wallet.Sync: [object Object]"
 * console noise (effect's Console.error routes through global console.error).
 * We count these so retry decisions can note them, and emit a single
 * sanitized line instead of the useless raw object.
 */
function installSyncNoiseFilter(): { restore: () => void; count: () => number } {
  const origErr = console.error.bind(console);
  let count = 0;
  const isNoise = (args: unknown[]): boolean => {
    if (typeof args[0] === 'string' && /^wallet\.sync\b/i.test(args[0])) return true;
    return args.some(
      (x) =>
        x != null &&
        typeof x === 'object' &&
        ((x as any)._tag === 'Wallet.Sync' || (x as any).name === 'SyncWalletError'),
    );
  };
  console.error = ((...args: unknown[]) => {
    if (isNoise(args)) {
      count += 1;
      return;
    }
    origErr(...args);
  }) as typeof console.error;
  return { restore: () => { console.error = origErr as typeof console.error; }, count: () => count };
}

/**
 * Sync the dedicated Preprod wallet with bounded retries + backoff, reusing
 * (never resetting) the persisted state under `.midnight-wallet-state/preprod/`.
 */
async function syncPreprodWallet(cfg: NetworkConfig, seed: string): Promise<SyncOutcome> {
  const rawBudget = Number(process.env.CJGATE_PREPROD_SYNC_TIMEOUT_MS);
  const budgetMs = Number.isFinite(rawBudget) && rawBudget > 0 ? rawBudget : 8 * 60_000;
  const rawStall = Number(process.env.CJGATE_PREPROD_SYNC_STALL_MS);
  const stallMs = Number.isFinite(rawStall) && rawStall > 0 ? rawStall : 75_000;
  const rawAttempts = Number(process.env.CJGATE_PREPROD_SYNC_ATTEMPTS);
  const maxAttempts = Number.isFinite(rawAttempts) && rawAttempts >= 1 ? Math.min(rawAttempts, 10) : 4;
  const backoffMs = [0, 3_000, 8_000, 15_000, 25_000, 40_000];

  const noise = installSyncNoiseFilter();
  const started = Date.now();
  let latestFacadeState: unknown = null;
  let latestProgress: SyncProgressView | null = null;
  let bestApplied = 0n;
  let bestHighest = 0n;
  let attempt = 0;
  let consecutiveDeadAttempts = 0; // attempts that ended with zero forward progress

  try {
    while (attempt < maxAttempts && Date.now() - started < budgetMs) {
      attempt += 1;
      const appliedAtAttemptStart = bestApplied;
      const highestAtAttemptStart = bestHighest;

      if (attempt > 1) {
        const wait = backoffMs[Math.min(attempt - 1, backoffMs.length - 1)];
        const errs = noise.count();
        console.log(
          `  retrying sync (attempt ${attempt}/${maxAttempts})` +
            (errs ? ` — ${errs} transient SDK sync error(s) so far` : '') +
            ` — backoff ${Math.round(wait / 1000)}s`,
        );
        await sleep(Math.min(wait, Math.max(0, budgetMs - (Date.now() - started))));
      } else {
        console.log(`  sync attempt ${attempt}/${maxAttempts}...`);
      }
      if (Date.now() - started >= budgetMs) break;

      const walletCtx = await createWallet({ network: NETWORK, networkConfig: cfg, seed });
      if (attempt === 1) {
        const restored = Object.values(walletCtx.restored).filter(Boolean).length;
        if (restored > 0) {
          console.log(`  resumed ${restored}/3 child wallets from .midnight-wallet-state/preprod/`);
        }
      }

      let lastKey = '';
      let lastProgressAt = Date.now();
      let waitRejected = false;

      const sub = walletCtx.wallet.state().subscribe({
        next: (fs: unknown) => {
          latestFacadeState = fs;
          const p = progressOf(fs);
          latestProgress = p;
          const key = progressKey(p);
          if (key !== lastKey) {
            lastKey = key;
            lastProgressAt = Date.now();
          }
          const a = appliedSum(p);
          if (a > bestApplied) bestApplied = a;
          const h = p.unshielded.highest + p.shielded.highest + p.dust.highest;
          if (h > bestHighest) bestHighest = h;
        },
        error: () => { /* facade state() is retry-wrapped and should not error */ },
      });

      const ticker = setInterval(() => {
        const p = latestProgress;
        const elapsed = Math.round((Date.now() - started) / 1000);
        if (!p) {
          process.stdout.write(`\r  still syncing... (${elapsed}s, connecting)                        `);
          return;
        }
        const g = (c: ChildProgress) => `${c.applied}/${c.highest}`;
        process.stdout.write(
          `\r  still syncing... (${elapsed}s)  u ${g(p.unshielded)}  s ${g(p.shielded)}  d ${g(p.dust)}        `,
        );
      }, 5000);
      const persister = setInterval(() => {
        void persistWalletState(NETWORK, walletCtx).catch(() => {});
      }, 45_000);

      const result: 'synced' | 'stalled' | 'budget' = await new Promise((resolve) => {
        let done = false;
        const finish = (r: 'synced' | 'stalled' | 'budget') => {
          if (done) return;
          done = true;
          resolve(r);
        };
        walletCtx.wallet
          .waitForSyncedState()
          .then(() => finish('synced'))
          .catch(() => {
            waitRejected = true;
          });
        const poll = setInterval(() => {
          if (done) {
            clearInterval(poll);
            return;
          }
          const now = Date.now();
          const p = latestProgress;
          if (p && p.unshielded.complete && p.shielded.complete && p.dust.complete) {
            clearInterval(poll);
            finish('synced');
            return;
          }
          if (now - started >= budgetMs) {
            clearInterval(poll);
            finish('budget');
            return;
          }
          if (now - lastProgressAt >= stallMs) {
            clearInterval(poll);
            finish('stalled');
            return;
          }
          if (waitRejected && now - lastProgressAt >= 15_000) {
            clearInterval(poll);
            finish('stalled');
            return;
          }
        }, 2000);
      });

      clearInterval(ticker);
      clearInterval(persister);
      sub.unsubscribe();
      process.stdout.write('\r' + ' '.repeat(72) + '\r');

      await persistWalletState(NETWORK, walletCtx);
      await walletCtx.wallet.stop().catch(() => {});

      if (result === 'synced') {
        return {
          status: 'synced',
          facadeState: latestFacadeState,
          progress: latestProgress,
          attempts: attempt,
          elapsedMs: Date.now() - started,
          syncErrorCount: noise.count(),
        };
      }
      const progressedThisAttempt =
        bestApplied > appliedAtAttemptStart || bestHighest > highestAtAttemptStart;
      consecutiveDeadAttempts = progressedThisAttempt ? 0 : consecutiveDeadAttempts + 1;

      if (result === 'budget') break;
      console.log(
        `  sync attempt ${attempt} stalled (no progress for ${Math.round(stallMs / 1000)}s` +
          `${waitRejected ? ', SDK sync stream errored' : ''}).`,
      );
    }

    // Classify. `consecutiveDeadAttempts >= maxAttempts` means every attempt
    // made zero forward progress — a stuck child / unreachable Preprod — so
    // surface it as a permanent failure rather than "just re-run".
    const nothingEverAdvanced = bestApplied === 0n && bestHighest === 0n;
    if (consecutiveDeadAttempts >= maxAttempts || nothingEverAdvanced) {
      return {
        status: 'failed',
        facadeState: latestFacadeState,
        progress: latestProgress,
        attempts: attempt,
        elapsedMs: Date.now() - started,
        syncErrorCount: noise.count(),
        reason: nothingEverAdvanced
          ? 'no sync progress at all against Preprod after bounded retries — the Preprod indexer/RPC is ' +
            'unreachable, or the wallet SDK could not decode the indexer response'
          : `${consecutiveDeadAttempts} consecutive sync attempt(s) made no forward progress — a wallet ` +
            'sync stream is stuck (see per-child progress below)',
      };
    }
    return {
      status: 'progressing',
      facadeState: latestFacadeState,
      progress: latestProgress,
      attempts: attempt,
      elapsedMs: Date.now() - started,
      syncErrorCount: noise.count(),
    };
  } finally {
    noise.restore();
  }
}

// ── init ─────────────────────────────────────────────────────────────────────
async function cmdInit(): Promise<void> {
  scrubImportedWalletEnv();
  const cfg = NETWORK_CONFIGS[NETWORK];

  const before = persistedPreprodWallet();
  const wallet = keepActiveNetwork(() => getOrCreateWallet(NETWORK)); // creates + persists if missing; no phrase printed
  if (wallet.created && !before) {
    console.log('Created a new dedicated CJGate Preprod wallet.');
    console.log('Its recovery phrase is stored in .midnight-state.json (gitignored, mode 0600).');
    console.log('Back up that file if you need recovery — the phrase is never printed.');
  } else {
    console.log('Reusing the existing dedicated CJGate Preprod wallet.');
  }
  console.log('');

  const address = deriveUnshieldedAddress(wallet.seed, NETWORK);
  console.log(`Preprod wallet address: ${address}`);
  console.log('');

  console.log('Syncing the wallet against Preprod (reuses .midnight-wallet-state/preprod/)...');
  const res = await syncPreprodWallet(cfg, wallet.seed);
  console.log('');

  // ── failed permanently ────────────────────────────────────────────────────
  if (res.status === 'failed') {
    console.error(
      `Preprod wallet sync FAILED after ${res.attempts} attempt(s) / ${Math.round(res.elapsedMs / 1000)}s.`,
    );
    console.error(`  reason: ${res.reason}`);
    if (res.syncErrorCount > 0) {
      console.error(`  wallet SDK reported ${res.syncErrorCount} internal "Wallet.Sync" error(s) (payload withheld).`);
    }
    if (res.progress) printSyncProgress(res.progress);
    console.error('  The persisted wallet state under .midnight-wallet-state/preprod/ is intact — nothing was reset.');
    console.error(`  Check Preprod status:  indexer ${cfg.indexer}`);
    console.error('  Then retry:  CJGATE_PREPROD_SYNC_TIMEOUT_MS=1800000 npm run cjgate:preprod:init');
    process.exit(3);
  }

  // ── still progressing (not an error) ──────────────────────────────────────
  if (res.status === 'progressing') {
    console.log(
      `Sync is progressing but not complete after ${res.attempts} attempt(s) / ` +
        `${Math.round(res.elapsedMs / 1000)}s — progress was cached.`,
    );
    if (res.syncErrorCount > 0) {
      console.log(`  (${res.syncErrorCount} transient SDK sync error(s) were retried during this run)`);
    }
    if (res.progress) printSyncProgress(res.progress);
    reportBalance(res.facadeState, res.progress, address, cfg, true);
    console.log('');
    console.log('Re-run to resume — it picks up from the saved point:');
    console.log('  CJGATE_PREPROD_SYNC_TIMEOUT_MS=1800000 npm run cjgate:preprod:init');
    process.exit(0);
  }

  // ── fully synced ─────────────────────────────────────────────────────────
  console.log(`Fully synced in ${res.attempts} attempt(s) / ${Math.round(res.elapsedMs / 1000)}s.`);
  console.log('');
  reportBalance(res.facadeState, res.progress, address, cfg, false);
  process.exit(0);
}

/**
 * Report ONLY public balance info. The unshielded tNIGHT balance is trusted
 * once the unshielded child reports `complete`, even if shielded/dust are
 * still catching up. DUST is reported only on a full sync.
 */
function reportBalance(
  fs: unknown,
  p: SyncProgressView | null,
  address: string,
  cfg: NetworkConfig,
  partial: boolean,
): void {
  const raw = unshieldedToken().raw;
  const tNight = toBig((fs as any)?.unshielded?.balances?.[raw]);
  // `partial === false` means the engine confirmed a full facade sync
  // (facade.waitForSyncedState resolved); trust that over a possibly-stale
  // last state snapshot.
  const unshieldedDone = !partial || Boolean(p?.unshielded.complete);

  if (unshieldedDone) {
    console.log(
      `Unshielded tNIGHT balance: ${tNight.toLocaleString()} (smallest unit)` +
        (partial ? '   [unshielded sync complete; shielded/dust still catching up]' : ''),
    );
  } else {
    const u = p?.unshielded;
    console.log(
      `Unshielded tNIGHT balance not final yet (unshielded sync ${u?.applied ?? 0n}/${u?.highest ?? 0n}).`,
    );
  }

  if (!partial) {
    let dust = 0n;
    try {
      dust = toBig((fs as any)?.dust?.balance?.(new Date()));
    } catch {
      /* ignore */
    }
    console.log(`DUST balance: ${dust.toLocaleString()} (smallest unit)`);
  }

  console.log('');
  if (unshieldedDone && tNight === 0n) {
    console.log('This wallet is not funded yet. Fund it, then re-run:');
    console.log(`  faucet:  ${cfg.faucet}`);
    console.log(`  address: ${address}`);
    console.log('No funds have been requested automatically.');
  } else if (!partial) {
    console.log('Wallet is funded and fully synced. Next: `npm run cjgate:preprod:deploy`.');
  } else if (unshieldedDone) {
    console.log('Unshielded funds are confirmed. Re-run to finish syncing before `npm run cjgate:preprod:deploy`.');
  }
}

// ── address ──────────────────────────────────────────────────────────────────
function cmdAddress(): void {
  scrubImportedWalletEnv();
  const w = persistedPreprodWallet();
  if (!w) die('no dedicated CJGate Preprod wallet yet — run: npm run cjgate:preprod:init');
  console.log(deriveUnshieldedAddress(w.seed, NETWORK));
  process.exit(0);
}

// ── deploy ───────────────────────────────────────────────────────────────────
function cmdDeploy(): void {
  const childEnv = scrubImportedWalletEnv();
  if (!persistedPreprodWallet()) {
    die('no dedicated CJGate Preprod wallet yet — run: npm run cjgate:preprod:init (and fund it) first');
  }
  console.log('Deploying the current CJGate contract to Preprod...');
  console.log('(this uses the scaffold deploy flow: wallet sync, DUST registration, faucet wait if unfunded)');
  console.log('');
  try {
    execFileSync('npm', ['run', 'deploy', '--', '--network', NETWORK], {
      cwd: repoRoot,
      stdio: 'inherit',
      env: childEnv,
    });
  } catch {
    die('deploy did not complete (see output above)', 1);
  }
  const dep = getDeployment(NETWORK);
  if (!dep?.address || dep.contract !== 'cjgate') {
    die('deploy finished but no cjgate Preprod address was recorded');
  }
  console.log('');
  console.log(`CJGate Preprod contract address: ${dep.address}`);
  console.log('Recorded in .midnight-state.json under deployments.preprod (distinct from deployments.undeployed).');
  console.log('Next: `npm run cjgate:preprod:live -- --source fixtures/clean`');
  process.exit(0);
}

// ── live ─────────────────────────────────────────────────────────────────────
function cmdLive(rest: string[]): void {
  const childEnv = scrubImportedWalletEnv();
  if (!persistedPreprodWallet()) {
    die('no dedicated CJGate Preprod wallet yet — run: npm run cjgate:preprod:init first');
  }
  if (!getDeployment(NETWORK)?.address) {
    die('no CJGate Preprod deployment — run: npm run cjgate:preprod:deploy first');
  }
  const args = ['run', 'cjgate:live', '--', '--network', NETWORK, ...rest];
  try {
    execFileSync('npm', args, { cwd: repoRoot, stdio: 'inherit', env: childEnv });
  } catch (e) {
    // Propagate cjgate:live's exit code (1 = BLOCK, 2 = setup failure).
    const code = (e as { status?: number }).status ?? 1;
    process.exit(code);
  }
  process.exit(0);
}

// ── dispatch ─────────────────────────────────────────────────────────────────
async function main(): Promise<void> {
  const sub = process.argv[2];
  const rest = process.argv.slice(3);
  switch (sub) {
    case 'init':
      return cmdInit();
    case 'address':
      return cmdAddress();
    case 'deploy':
      return cmdDeploy();
    case 'live':
      return cmdLive(rest);
    default:
      die(`unknown subcommand "${sub ?? ''}" — use: init | address | deploy | live`, 2);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(2);
});
